config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"

  mount MissionControl::Jobs::Engine, at: "/jobs"
  mount Litestream::Engine, at: "/litestream"
  mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.development?

  resource :registration, only: %i[ new create ]
  resource :session
  resources :passwords, param: :token

  resource :oauth, only: %i[ new create ]

  resources :reportings, only: %i[ new create ]

  resource :user, only: %i[ edit update destroy ]
  resources :posts, except: %i[ index show ] do
    resources :broadcasts, module: :posts, only: :create
  end

  scope module: :posts do
    resources :drafts, only: :index
    resources :archives, only: :index
  end

  resources :authors, path: "", param: :slug, only: [] do
    resources :posts, path: "", param: :slug, only: %i[ index show ]
    resources :subscribers, param: :token, only: %i[ create ] do
      get :confirmed
      get :unsubscribe
    end
  end
end

app/views/shared/_flash.html.erb
<% if notice.present? %>
  <button type="button" id="notice" class="absolute top-24 left-0 right-0 mx-auto w-64 py-2 px-4 bg-green-500 rounded-full text-sm text-white font-medium transition transform duration-1000"
    data-controller="flash" data-action="click->flash#hide"
    data-transition-enter-from="opacity-0 -translate-y-6"
    data-transition-enter-to="opacity-100 translate-y-0"
    data-transition-leave-from="opacity-100 translate-y-0"
    data-transition-leave-to="opacity-0 -translate-y-6">
    <%= notice %>
  </button>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class="mx-auto max-w-3xl flex items-center justify-between  p-4" aria-label="Global">
    <div class="flex lg:flex-1">
      <%= link_to authenticated? ? author_posts_path(Current.user.slug) : root_path do %>
        <span class="sr-only">Blog</span>
        <%= image_tag "message-square-text.svg", size: 30, alt: "logo" %>
      <% end %>
    </div>
    <div class="flex items-center gap-8">
      <% if authenticated? %>
        <%= link_to new_post_path, class: "btn btn-primary text-sm py-1 px-4" do %>
          <div class="flex items-center gap-x-1.5">
            <%= image_tag "pencil.svg", size: 16, style: "filter:  brightness(0) invert(1);", alt: "Pencil" %>
            <span>Write</span>
          </div>
        <% end %>
        <div class="relative flex" data-controller="dropdown">
          <button type="button" class="font-semibold text-base text-gray-900 cursor-pointer" data-action="dropdown#toggle click@window->dropdown#hide">
            <%= image_tag Current.user.avatar.presence || "user-circle.svg", size: 30, class: "rounded-full h-7.5", alt: "Avatar" %>
          </button>
          <div class="absolute right-0 top-10 z-10 rounded shadow-md bg-gray-100 min-w-64 transition transform origin-top-right hidden" data-dropdown-target="menu" data-transition-enter-from="opacity-0 scale-95" data-transition-enter-to="opacity-100 scale-100" data-transition-leave-from="opacity-100 scale-100" data-transition-leave-to="opacity-0 scale-95">
            <ul class="flex flex-col gap-y-2 p-4">
              <li>
                <%= link_to drafts_path, class: "flex gap-x-2 rounded-md py-1 px-2 hover:bg-gray-200" do %>
                  <%= image_tag "book-marked.svg", size: 16, alt: "Book" %>
                  <span class="text-base font-semibold text-gray-800">Posts</span>
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_path, class: "flex gap-x-2 rounded-md py-1 px-2 hover:bg-gray-200" do %>
                  <%= image_tag "user-pen.svg", size: 16, alt: "User" %>
                  <span class="text-base font-semibold text-gray-800">Profile</span>
                <% end %>
              </li>
            </ul>
            <hr />
            <div class="p-4">
              <%= button_to "Sign out", Current.session, method: :delete, class: "rounded-full bg-gray-500 hover:bg-gray-400 font-normal text-sm text-white py-1 w-full cursor-pointer" %>
            </div>
          </div>
        </div>
      <% else %>
        <%= link_to "Sign in", new_session_path, class: "text-sm text-gray-600 font-semibold" %>
        <%= link_to "Get started", new_registration_path, class: "btn btn-primary text-sm py-1 px-3" %>
      <% end %>
    </div>
  </nav>
</header>