config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"

  mount MissionControl::Jobs::Engine, at: "/jobs"
  mount Litestream::Engine, at: "/litestream"
  mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.development?

  resource :registration, only: %i[ new create ]
  resource :session
  resources :passwords, param: :token

  resource :oauth, only: %i[ new create ]

  resources :reportings, only: %i[ new create ]

  resource :user, only: %i[ edit update destroy ]
  resources :posts, except: %i[ index show ] do
    resources :broadcasts, module: :posts, only: :create
  end

  scope module: :posts do
    resources :drafts, only: :index
    resources :archives, only: :index
  end

  resources :authors, path: "", param: :slug, only: [] do
    resources :posts, path: "", param: :slug, only: %i[ index show ]
    resources :subscribers, param: :token, only: %i[ create ] do
      get :confirmed
      get :unsubscribe
    end
  end
end

app/models/concerns/post/sluggable.rb
module Post::Sluggable
  extend ActiveSupport::Concern

  included do
    before_save :set_slug, if: -> { slug.blank? }
  end

  private
    def set_slug
      self.slug = "#{title.parameterize}-#{SecureRandom.hex(6)}"
    end
end

app/models/post.rb
class Post < ApplicationRecord
  include Availability, Sluggable

  enum :status, %i[ draft published archived ], default: :draft, validate: true
  has_rich_text :body

  belongs_to :user, default: -> { Current.user }

  validates :title, presence: true

  after_update :mark_as_published, if: -> { saved_change_to_status? && self.published? }

  private
    def mark_as_published
      self.touch(:published_at)
    end
end

app/controllers/posts/archives_controller.rb
class Posts::ArchivesController < ApplicationController
  def index
    @posts = Current.user.posts.archived.order(published_at: :desc)
  end
end

app/controllers/posts/broadcasts_controller.rb
class Posts::BroadcastsController < ApplicationController
  def create
    post = Post.find(params.expect(:post_id))
    return head :forbidden unless post.published?

    PostsMailer.broadcast(post).deliver_later
    redirect_to author_post_path(post.user.slug, post.slug), notice: "Post was successfully broadcasted."
  end
end

app/controllers/posts/drafts_controller.rb
class Posts::DraftsController < ApplicationController
  def index
    @posts = Current.user.posts.draft.order(updated_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_author, only: %i[ index show ]
  before_action :set_post, only: %i[ edit update destroy ]
  before_action -> { ensure_permissions_for @post }, only: %i[ edit update destroy ]

  def index
    set_page_and_extract_portion_from @author.posts.published, ordered_by: { published_at: :desc, id: :desc }, per_page: 24
  end

  def show
    @post = @author.posts.find_by!(slug: params.expect(:slug))
    head :forbidden unless @post.published? || (authenticated? && @post.user == Current.user)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to author_post_path(@post.user.slug, @post.slug), notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to author_post_path(@post.user.slug, @post.slug), notice: "Post was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!
    redirect_to author_posts_path(@post.user.slug), notice: "Post was successfully destroyed.", status: :see_other
  end

  private
    def set_author
      @author = User.find_by!(slug: params.expect(:author_slug))
    end

    def set_post
      @post = Post.find(params.expect(:id))
    end

    def post_params
      params.expect(post: [ :title, :body, :status ])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-12">
    <%= form.text_field :title, autofocus: true, class: "form-control form-control-lg font-bold text-center", placeholder: "e.g. Hello world!" %>
  </div>

  <div class="my-12">
    <%= form.rich_textarea :body , class: "form-control min-h-40", data: { controller: "trix", trix_unused_components_value: [".trix-button--icon-heading-1", ".trix-button-group--file-tools", ".trix-button-group--history-tools"] }, placeholder: "..." %>
  </div>

  <div class="text-center">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article id="<%= dom_id post %>" class="relative border rounded mb-8 p-16">
  <div class="text-center">
    <div class="text-sm"><%= l post.published_at, format: :full_date if post.published_at.present? %></div>
    <h2 class="font-semibold text-xl text-primary-500"><%= post.title %></h2>
  </div>
  <div class="my-8"><%= truncate(post.body.to_plain_text, length: 250) %></div>
  <div class="text-center">
    <%= link_to "Read more", author_post_path(post.user.slug, post.slug), class: "border rounded-full py-2 px-4 after:absolute after:inset-0" %>
  </div>
</article>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", post: @post %>

  <fieldset class="border-2 border-danger-600 rounded-md p-8 mt-24">
    <legend class="font-semibold text-xl text-danger-600">Danger zone</legend>

    <%= form_with model: @post, method: :delete, class: "contents", data: { controller: "confirmation" } do |form| %>
      <div class="mb-5">
        <label for="confirmation" class="form-label">Type "DELETE" to confirm</label>
        <input id="confirmation" class="form-control font-semibold" placeholder="DELETE" data-confirmation-target="input" data-confirmation-content="DELETE" data-action="confirmation#check" />
      </div>
      <%= form.submit "Destroy this post", class: "btn btn-sm btn-danger", disabled: true, data: { confirmation_target: "item" } %>
    <% end %>
  </fieldset>
</div>

app/views/posts/index.html.erb
<% content_for :title, @author.name %>

<% content_for :head do %>
  <%= auto_discovery_link_tag :atom, author_posts_url(format: :atom), title: "Feed" %>

  <%= tag.meta property: "description", content: @author.name %>
  <%= tag.meta property: "robots", content: "index, follow" %>

  <%= tag.meta property: "og:site_name", content: "Blog" %>
  <%= tag.meta property: "og:type", content: "article" %>
  <%= tag.meta property: "og:url", content: author_posts_url(@author.slug) %>
  <%= tag.meta property: "og:title", content: @author.name %>
  <%= tag.meta property: "og:description", content: @author.name %>
  <%= tag.meta property: "og:image", content: @author.avatar.present? ? url_for(@author.avatar) : image_url("user-circle.svg") %>

  <%= tag.meta property: "twitter:title", content: @author.name %>
  <%= tag.meta property: "twitter:description", content: @author.name %>
  <%= tag.meta property: "twitter:image", content: @author.avatar.present? ? url_for(@author.avatar) : image_url("user-circle.svg") %>
  <%= tag.meta property: "twitter:card", content: "summary_large_image" %>
<% end %>

<div class="w-full">
  <header class="text-center">
    <%= link_to author_posts_path(@author.slug) do %>
      <%= image_tag @author.avatar.presence || "user-circle.svg", size: "48", class: "inline-flex rounded-full object-cover h-12" %>
      <p class="font-bold text-xl text-primary-400 mt-2"><%= @author.name.upcase %></p>
    <% end %>
    <div class="mt-8"><%= @author.bio %></div>
  </header>

  <section id="posts" class="mt-16">
    <%= render @page.records %>
  </section>

  <% unless @page.last? %>
    <div class="text-center mt-24">
      <%= link_to "Next page", author_posts_path(@author.slug, page: @page.next_param), class: "border rounded-full py-2 px-4" %>
    </div>
  <% end %>

  <% if authenticated? %>
    <div class="text-center mt-24">
      <%= link_to "View archived posts", archives_path, class: "border rounded-full py-2 px-4" %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", post: @post %>
</div>

app/views/posts/show.html.erb
<% content_for(:title) { @post.title } %>

<% content_for :head do %>
  <%= auto_discovery_link_tag :atom, author_posts_url(format: :atom), title: "Feed" %>

  <%= tag.meta name: "author", content: @author.name %>
  <%= tag.meta name: "description", content: truncate(@post.body.to_plain_text, length: 250) %>
  <%= tag.meta name: "robots", content: "index, follow" %>

  <%= tag.meta property: "og:site_name", content: "Blog" %>
  <%= tag.meta property: "og:type", content: "article" %>
  <%= tag.meta property: "og:url", content: author_post_url(@author.slug, @post.slug) %>
  <%= tag.meta property: "og:title", content: @post.title %>
  <%= tag.meta property: "og:description", content: truncate(@post.body.to_plain_text, length: 250) %>
  <%= tag.meta property: "og:image", content: @author.avatar.present? ? url_for(@author.avatar) : image_url("user-circle.svg") %>

  <%= tag.meta property: "twitter:title", content: @post.title %>
  <%= tag.meta property: "twitter:description", content: truncate(@post.body.to_plain_text, length: 250) %>
  <%= tag.meta property: "twitter:image", content: @author.avatar.present? ? url_for(@author.avatar) : image_url("user-circle.svg") %>
  <%= tag.meta property: "twitter:card", content: "summary_large_image" %>
<% end %>

<div class="relative w-full">
  <header class="text-center mb-16">
    <%= link_to author_posts_path(@author.slug) do %>
      <%= image_tag @author.avatar.presence || "user-circle.svg", size: "48", class: "inline-flex rounded-full object-cover h-12", alt: "Avatar" %>
      <p class="font-bold text-xl text-primary-400 mt-2"><%= @author.name.upcase %></p>
    <% end %>
  </header>

  <div class="relative">
    <p class="text-center"><%= l @post.published_at, format: :full_date if @post.published_at.present? %></p>
    <h1 class="font-bold text-4xl text-center"><%= @post.title %></h1>

    <% if @post.published? %>
      <div class="absolute top-0 bottom-0 end-0 flex justify-center">
        <div class="relative flex" data-controller="dropdown">
          <button type="button" class="text-base text-gray-900 font-semibold" data-action="dropdown#toggle click@window->dropdown#hide">
            <%= image_tag "share.svg", size: 20, alt: "Share" %>
          </button>
          <div class="absolute right-0 top-12 border rounded shadow bg-white min-w-64 transition transform origin-top-right hidden" data-dropdown-target="menu" data-transition-enter-from="opacity-0 scale-95" data-transition-enter-to="opacity-100 scale-100" data-transition-leave-from="opacity-100 scale-100" data-transition-leave-to="opacity-0 scale-95">
            <ul class="flex flex-col gap-y-3 p-4">
              <li data-controller="clipboard" data-clipboard-success-content-value="Copied!">
                <%= hidden_field_tag :original_url, request.original_url, data: { clipboard_target: "source" } %>
                <button type="button" class="flex items-center gap-x-2 text-base text-gray-600 font-normal hover:text-gray-900" data-action="click->clipboard#copy" data-clipboard-target="button">
                  <%= image_tag "link.svg", size: 20 %>
                  Copy link
                </button>
              </li>
              <li>
                <%= button_tag class: "flex items-center gap-x-2 text-base text-gray-600 font-normal hover:text-gray-900", hidden: true, data: { controller: "web-share", action: "web-share#share", web_share_url_value: request.url, web_share_text_value: "View this post online", web_share_title_value: "Hit this link to read this post online." } do %>
                  <%= image_tag "share-2.svg", size: 20 %>
                  Share
                <% end %>
              </li>
              <li>
                <%= link_to new_reporting_path, class: "block text-base text-gray-600 font-normal hover:text-gray-900" do %>
                  <div class="flex items-center gap-x-2">
                    <%= image_tag "triangle-alert.svg", size: 20 %>
                    <span>Report post</span>
                  </div>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <section class="my-16">
    <article><%= @post.body %></article>
  </section>

  <section class="text-center">
    <%= form_with scope: :subscriber, url: author_subscribers_path(@author.slug), class: "contents" do |form| %>
      <%= form.label :email_address, "Subscribe to get future posts via email", class: "block" %>
      <div class="inline-flex mt-4">
        <%= form.email_field :email_address, required: true, placeholder: "Enter your email address", class: "form-control border border-r-transparent rounded-l-full" %>
        <%= form.submit "Subscribe", class: "btn btn-primary rounded-l-none" %>
      </div>
    <% end %>
  </section>

  <% content_for :footer do %>
    <nav class="flex justify-center py-8">
      <%= link_to "Made with Rails", "https://rubyonrails.org/", target: "_blank", class: "text-sm text-gray-500 hover:text-primary-500" %>
    </nav>
  <% end %>

  <% if authenticated? %>
    <div class="absolute top-0 right-0">
      <div class="relative flex" data-controller="dropdown">
        <button type="button" class="text-base text-gray-900 font-semibold" data-action="dropdown#toggle click@window->dropdown#hide">
          <%= image_tag "ellipsis-horizontal.svg", size: 28 %>
        </button>
        <div class="absolute right-0 top-8 z-10 border rounded shadow bg-white min-w-64 transition transform origin-top-right hidden" data-dropdown-target="menu" data-transition-enter-from="opacity-0 scale-95" data-transition-enter-to="opacity-100 scale-100" data-transition-leave-from="opacity-100 scale-100" data-transition-leave-to="opacity-0 scale-95">
          <ul class="flex flex-col gap-y-2 p-4">
            <li><%= link_to "Edit this post", edit_post_path(@post), class: "block text-base text-gray-500 font-normal hover:text-primary-500 hover:font-semibold" %></li>

            <% if @post.draft? || @post.archived? %>
              <div data-controller="dialog" data-action="click->dialog#backdropClose">
                <button type="button" class="block text-base text-gray-500 font-normal hover:text-primary-500 hover:font-semibold" data-action="click->dialog#open">Publish this post</button>

                <dialog class="relative rounded-lg shadow-lg" data-dialog-target="dialog">
                  <form method="dialog">
                    <button class="absolute right-4 top-4">
                      <%= image_tag "x-mark.svg", size: 24, aria: { hidden: true } %>
                      <span class="sr-only">Close</span>
                    </button>
                  </form>

                  <div class="flex flex-col gap-6 text-center py-12 px-8">
                    <p class="text-lg text-gray-500">Are you sure you want to publish this post?</p>
                    <%= button_to "Publish", @post, method: :patch, params: { post: { status: :published } }, class: "btn btn-primary px-24" %>
                  </div>
                </dialog>
              </div>
            <% end %>

            <% if @post.published? %>
              <%= button_to "Broadcast this post", post_broadcasts_path(@post), method: :post, class: "block text-base text-gray-500 font-normal hover:text-primary-500 hover:font-semibold" %>
              <%= button_to "Archive this post", @post, method: :patch, params: { post: { status: :archived } }, class: "block text-base text-gray-500 font-normal hover:text-primary-500 hover:font-semibold" %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>

  <% if @post.archived? %>
    <div class="absolute top-20 left-20 border-4 border-red-500 font-extrabold text-xl text-red-500 p-0.5 -rotate-12">ARCHIVED</div>
  <% end %>
</div>